# Generated by Django 2.2.6 on 2019-10-08 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='to',
        ),
        migrations.RemoveField(
            model_name='message',
            name='to',
        ),
        migrations.AddField(
            model_name='memory',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='memory_created_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='message_created_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
