# Generated by Django 2.2.6 on 2019-10-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='seen_at',
            field=models.DateTimeField(null=True),
        ),
    ]
