# Generated by Django 2.2.6 on 2019-10-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0002_auto_20191004_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
