# Generated by Django 2.2.6 on 2019-10-11 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0002_auto_20191009_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritememory',
            name='memory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='favourite_memory', to='memories.Memory'),
        ),
        migrations.AlterField(
            model_name='favouritemessage',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='favourite_message', to='memories.Message'),
        ),
        migrations.AlterField(
            model_name='memoryreply',
            name='memory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='memory_reply', to='memories.Memory'),
        ),
        migrations.AlterField(
            model_name='messagereply',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='message_reply', to='memories.Message'),
        ),
    ]
