# Generated by Django 2.2.6 on 2019-10-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0003_auto_20191011_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
