# Generated by Django 2.2.6 on 2019-10-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0004_auto_20191004_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
