# Generated by Django 2.2.6 on 2019-10-12 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0004_message_published'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favouritememory',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='favouritemessage',
            unique_together=set(),
        ),
    ]
