# Generated by Django 2.2.6 on 2019-10-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0005_auto_20191004_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memory',
            old_name='created_date',
            new_name='created_datetime',
        ),
        migrations.RenameField(
            model_name='memory',
            old_name='updated_date',
            new_name='updated_datetime',
        ),
        migrations.AddField(
            model_name='memory',
            name='seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memory',
            name='publish_date',
            field=models.DateField(unique=True),
        ),
    ]
