# Generated by Django 2.2.6 on 2019-11-20 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0005_auto_20191012_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memory',
            options={'ordering': ['-publish_date'], 'verbose_name': 'Memory', 'verbose_name_plural': 'Memories'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
    ]
