# Generated by Django 2.2.6 on 2019-11-20 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0006_auto_20191120_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-id']},
        ),
    ]
