# Generated by Django 2.2.6 on 2019-10-04 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0007_auto_20191004_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoryreply',
            name='memory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memory_reply', to='memories.Memory'),
        ),
    ]
