# Generated by Django 2.2.6 on 2019-11-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0008_auto_20191120_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
