# Generated by Django 2.2.6 on 2019-11-20 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0010_auto_20191120_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-id']},
        ),
    ]
