# Generated by Django 2.2.6 on 2019-12-27 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20191009_0459'),
        ('memories', '0011_auto_20191120_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='lovers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Lover'),
            preserve_default=False,
        ),
    ]
