# Generated by Django 2.2.6 on 2019-12-27 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20191009_0459'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memories', '0012_category_lovers'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialMessageSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200, unique=True)),
                ('lovers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Lover')),
            ],
            options={
                'verbose_name': 'Special Message source',
                'verbose_name_plural': 'Special Message sources',
                'ordering': ['source'],
            },
        ),
        migrations.CreateModel(
            name='SpecialMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=1024)),
                ('image', models.ImageField(upload_to='images')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_message_created_by', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memories.SpecialMessageSource')),
            ],
        ),
    ]
