# Generated by Django 2.2.6 on 2019-12-27 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0014_auto_20191227_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialmessage',
            old_name='created_by',
            new_name='lovers',
        ),
    ]
