# Generated by Django 2.2.6 on 2019-10-08 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('female', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='female_user', to=settings.AUTH_USER_MODEL, unique=True)),
                ('male', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='male_user', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
